### PR TITLE
Split one design&runtime package

### PR DESCRIPTION
**Pull request by ondrejpokorny**

### CODE REVIEW

**Comment by heX16** [comment]
I see call "RegisterUnitVirtualTrees" function (in registervirtualtreeview.pas), but i cant find where this function is declared.

What exactly does this PR do?
What problem does it solve and why is it needed?

And I see the "DrawButtonText" function being changed, and add new function "OnChange", and other changes - they do not relate to the topic of the PR. I think they need to be formalized by separate PRs.

**Comment by heX16** [comment]
@ondrejpokorny You can delete this PR and start all over again but more orderly?

**Comment by ondrejpokorny** [comment]
> @ondrejpokorny You can delete this PR and start all over again but more orderly?

I think so. It's strange to me why the new 3 commits (Multiple sort column support) appeared here - I did not intent to add them here.

Well, I am not very familiar with Git, that is the problem.

**Comment by ondrejpokorny** [comment]
OK, I closed this merge request. I hope it's OK.

**Pull request closed without merging**
